# This is a basic workflow to help you get started with Actions

name: Update Data

# Controls when the action will run. Triggers the workflow once every day at 14:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Code
      run: python updater.py
    
    - name: Update Repo
      run: |
        rm target -rf
        git config --global user.email "mateus.sakata@gmail.com"
        git config --global user.name "Piphi5"
        git clone https://.:${{secrets.TOKEN }}@github.com/Piphi5/MHM-Data target
        git fetch --unshallow target
        cp Data/* target
        cd target
        git add .
        git commit -m "Automatic Update"
        git push origin master --force
        
    
